In [ ]:
import pandas as pd
import numpy as np

### Creating the imaging TSV for UMichigan batch 1:

In [ ]:
directory1 = '/content/drive/MyDrive/powertools_umich_20230113.csv' #powertools output file for UMichigan batch 1
directory2 = '/content/all_imaging_studies_including_385_missing.csv' #all imaging study details provided by UMichigan and generated by me

In [ ]:
df1 = pd.read_csv(directory1)
df2 = pd.read_csv(directory2)

#### Grabbing all the studies in batch 1 using the powertools output file:

In [ ]:
studies_b1 = df1.drop_duplicates(subset='study_uid')

In [ ]:
studies_b1

,file_name,accession_number,acquisition_type,body_part_examined,case_ids,contrast_bolus_agent,contrast_bolus_agent_number,patient_position,convolution_kernel,detector_type,...,pixel_spacing,series_description,series_uid,slice_thickness,spacing_between_slices,spatial_resolution,study_description,study_uid,view_position,study_date
0,1.2.826.0.1.3680043.10.474.302028.12706.dcm,2,NaN,CHEST,302028-000002,NaN,NaN,NaN,NaN,SCINTILLATOR,...,NaN,CHEST AP,1.2.826.0.1.3680043.10.474.302028.7,NaN,NaN,0.125,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.6,AP,20170401
1,1.2.826.0.1.3680043.10.474.302028.40598.dcm,2,NaN,CHEST,302028-000003,NaN,NaN,NaN,NaN,SCINTILLATOR,...,NaN,CHEST AP,1.2.826.0.1.3680043.10.474.302028.11,NaN,NaN,0.125,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.10,AP,20180412
2,1.2.826.0.1.3680043.10.474.302028.74478.dcm,2,NaN,CHEST,302028-000003,Value Anonymized,NaN,NaN,NaN,SCINTILLATOR,...,NaN,W CHEST PA,1.2.826.0.1.3680043.10.474.302028.14,NaN,NaN,NaN,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.13,NaN,20180406
4,1.2.826.0.1.3680043.10.474.302028.83248.dcm,2,NaN,CHEST,302028-000004,NaN,NaN,NaN,NaN,SCINTILLATOR,...,NaN,NaN,1.2.826.0.1.3680043.10.474.302028.19,NaN,NaN,0.125,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.18,AP,20110517
5,1.2.826.0.1.3680043.10.474.302028.106944.dcm,2,NaN,CHEST,302028-000005,NaN,NaN,NaN,NaN,SCINTILLATOR,...,NaN,W Chest Lat.,1.2.826.0.1.3680043.10.474.302028.22,NaN,NaN,NaN,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.21,NaN,20141214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541206,1.2.826.0.1.3680043.10.474.302028.1593289.dcm,2,NaN,CHEST,302028-004296,NaN,NaN,NaN,NaN,SCINTILLATOR,...,NaN,W Chest p.a.,1.2.826.0.1.3680043.10.474.302028.1593291,NaN,NaN,NaN,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1593290,NaN,20191027
541208,1.2.826.0.1.3680043.10.474.302028.1593331.dcm,2,NaN,NaN,302028-004297,93ML ISO370,NaN,FFS,STANDARD,NaN,...,0.712891,CHEST 2 q 2 SAGITTAL,1.2.826.0.1.3680043.10.474.302028.1593333,1.25,NaN,NaN,CT CHEST W CONTRAST,1.2.826.0.1.3680043.10.474.302028.1593332,NaN,20160520
542180,1.2.826.0.1.3680043.10.474.302028.1595897.dcm,2,NaN,CHEST,302028-004298,NaN,NaN,NaN,NaN,SCINTILLATOR,...,NaN,W Chest p.a.,1.2.826.0.1.3680043.10.474.302028.1595899,NaN,NaN,NaN,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1595898,NaN,20140313
542182,1.2.826.0.1.3680043.10.474.302028.1595902.dcm,2,NaN,CHEST,302028-004299,NaN,NaN,NaN,NaN,SCINTILLATOR,...,NaN,CHEST AP,1.2.826.0.1.3680043.10.474.302028.1595904,NaN,NaN,0.125,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.1595903,AP,20111101
542183,1.2.826.0.1.3680043.10.474.302028.1595932.dcm,2,NaN,CHEST,302028-004300,NaN,NaN,NaN,NaN,SCINTILLATOR,...,NaN,W Chest a.p. PEDS Infant_c,1.2.826.0.1.3680043.10.474.302028.1595934,NaN,NaN,NaN,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1595933,NaN,20120405

#### There are 4932 studies in batch 1. Let's clean up this table a bit:

In [ ]:
studies_b1 = studies_b1[['case_ids', 'body_part_examined', 'modality', 'study_uid', 'study_description']]

In [ ]:
studies_b1.rename(columns={'modality': 'study_modality'}, inplace=True)

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [ ]:
studies_b1['submitter_id'] = studies_b1['study_uid']
studies_b1['cases'] = studies_b1['case_ids']
studies_b1['study_year_shifted'] = False

<ipython-input-8-f0a020716847>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  studies_b1['submitter_id'] = studies_b1['study_uid']
<ipython-input-8-f0a020716847>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  studies_b1['cases'] = studies_b1['case_ids']
<ipython-input-8-f0a020716847>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  studies_b1['study_year_shifted'] = False

In [ ]:
studies_b1

,case_ids,body_part_examined,study_modality,study_uid,study_description,submitter_id,cases,study_year_shifted
0,302028-000002,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.6,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.6,302028-000002,False
1,302028-000003,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.10,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.10,302028-000003,False
2,302028-000003,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.13,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.13,302028-000003,False
4,302028-000004,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.18,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.18,302028-000004,False
5,302028-000005,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.21,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.21,302028-000005,False
...,...,...,...,...,...,...,...,...
541206,302028-004296,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.1593290,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1593290,302028-004296,False
541208,302028-004297,NaN,CT,1.2.826.0.1.3680043.10.474.302028.1593332,CT CHEST W CONTRAST,1.2.826.0.1.3680043.10.474.302028.1593332,302028-004297,False
542180,302028-004298,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.1595898,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1595898,302028-004298,False
542182,302028-004299,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.1595903,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.1595903,302028-004299,False
542183,302028-004300,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.1595933,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1595933,302028-004300,False

#### Now that the table is cleaned up some, let's use the imaging details submitted by UMichigan (and also generated by me)to get more info:

In [ ]:
df2

,anon_mrn,age,anon_study_uid,anon_study_date,study_year,study_modality,study_description,body_part_examined,series_count
0,302028-000002,21,1.2.826.0.1.3680043.10.474.302028.6,0,2020,XR,XR CHEST PORTABLE 1 VIEW,NaN,NaN
1,302028-000008,57,1.2.826.0.1.3680043.10.474.302028.5689,-7,2020,XR,XR CHEST 2 VIEWS,NaN,NaN
2,302028-000005,46,1.2.826.0.1.3680043.10.474.302028.21,-2,2020,XR,XR CHEST 2 VIEWS,NaN,NaN
3,302028-000005,46,1.2.826.0.1.3680043.10.474.302028.9248,0,2020,XR,XR CHEST PORTABLE 1 VIEW,NaN,NaN
4,302028-000005,46,1.2.826.0.1.3680043.10.474.302028.5697,1,2020,XR,XR CHEST PORTABLE 1 VIEW,NaN,NaN
...,...,...,...,...,...,...,...,...,...
32717,302028-004180,64,1.2.826.0.1.3680043.10.474.302028.1520905,4,2020,NaN,NaN,NaN,NaN
32718,302028-004189,24,1.2.826.0.1.3680043.10.474.302028.1498580,3,2020,NaN,NaN,NaN,NaN
32719,302028-004223,23,1.2.826.0.1.3680043.10.474.302028.1529012,0,2020,NaN,NaN,NaN,NaN
32720,302028-004242,80,1.2.826.0.1.3680043.10.474.302028.1548483,672,2022,NaN,NaN,NaN,NaN
32721,302028-004271,68,1.2.826.0.1.3680043.10.474.302028.1563925,6,2020,NaN,NaN,NaN,NaN

#### Locating all the details for the studies in our batch. We're looking for the age at imaging, the days_to_study values, and the study year:

In [ ]:
study_details_b1 = df2.loc[df2.anon_study_uid.isin(studies_b1['study_uid'])]

In [ ]:
study_details_b1 = study_details_b1[['age','anon_study_uid','anon_study_date', 'study_year']]

In [ ]:
study_details_b1.rename(columns={'age': 'age_at_imaging', 'anon_study_date': 'days_to_study','anon_study_uid':'study_uid'}, inplace=True)

In [ ]:
study_details_b1

,age_at_imaging,study_uid,days_to_study,study_year
0,21,1.2.826.0.1.3680043.10.474.302028.6,0,2020
2,46,1.2.826.0.1.3680043.10.474.302028.21,-2,2020
22,82,1.2.826.0.1.3680043.10.474.302028.18,80,2020
26,62,1.2.826.0.1.3680043.10.474.302028.26,-7,2020
32,56,1.2.826.0.1.3680043.10.474.302028.13,-7,2020
...,...,...,...,...
32717,64,1.2.826.0.1.3680043.10.474.302028.1520905,4,2020
32718,24,1.2.826.0.1.3680043.10.474.302028.1498580,3,2020
32719,23,1.2.826.0.1.3680043.10.474.302028.1529012,0,2020
32720,80,1.2.826.0.1.3680043.10.474.302028.1548483,672,2022
32721,68,1.2.826.0.1.3680043.10.474.302028.1563925,6,2020

#### Let's merge these details with the studies_b1 table:

In [ ]:
studies_b1 = pd.merge(studies_b1, study_details_b1,  how='left', on=['study_uid'])

In [ ]:
studies_b1

,case_ids,body_part_examined,study_modality,study_uid,study_description,submitter_id,cases,study_year_shifted,age_at_imaging,days_to_study,study_year
0,302028-000002,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.6,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.6,302028-000002,False,21,0,2020
1,302028-000003,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.10,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.10,302028-000003,False,56,-1,2020
2,302028-000003,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.13,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.13,302028-000003,False,56,-7,2020
3,302028-000004,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.18,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.18,302028-000004,False,82,80,2020
4,302028-000005,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.21,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.21,302028-000005,False,46,-2,2020
...,...,...,...,...,...,...,...,...,...,...,...
4927,302028-004296,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.1593290,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1593290,302028-004296,False,57,0,2020
4928,302028-004297,NaN,CT,1.2.826.0.1.3680043.10.474.302028.1593332,CT CHEST W CONTRAST,1.2.826.0.1.3680043.10.474.302028.1593332,302028-004297,False,42,0,2020
4929,302028-004298,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.1595898,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1595898,302028-004298,False,29,0,2020
4930,302028-004299,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.1595903,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.1595903,302028-004299,False,57,3,2020
4931,302028-004300,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.1595933,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1595933,302028-004300,False,0,0,2020

#### Looks great. Let's now make sure the properties align with the MIDRC data model:

In [ ]:
studies_b1['body_part_examined'].unique()

array(['CHEST', nan, 'ABDOMEN', 'LSPINE'], dtype=object)

In [ ]:
studies_b1['study_modality'].unique()

array(['DX', 'CR', 'CT'], dtype=object)

In [ ]:
studies_b1['study_description'].unique()

array(['XR CHEST PORTABLE 1 VIEW', 'XR CHEST 2 VIEWS',
       'CT CHEST WO CONTRAST', 'XR CHEST MORNING ROUTINE PORTABLE',
       'CT CHEST W CONTRAST', 'XR CHEST LINE PLACEMENT PORTABLE',
       'XR CHEST PORTABLE 2 VIEWS - PEDS ONLY', 'XR CHEST 1 VIEW',
       'XR CHEST PORTABLE 1 VIEW - PEDS ONLY', 'XR CHEST PICC 1 VIEW',
       nan, 'XR CHEST MORNING ROUTINE PORTABLE PUMP',
       'XR CHEST PA AND LATERAL', 'XR CHEST LINE PLACEMENT PORTABLE PED',
       'CT CHEST LOW DOSE SCREENING', 'XR CHEST 3 VIEWS',
       'CT CHEST FOR NODULE'], dtype=object)

In [ ]:
studies_b1['study_year'].unique()

array([2020, 2021, 2022])

In [ ]:
studies_b1['age_at_imaging'].unique()

array([21, 56, 82, 46, 62, 85, 63, 47, 64, 70, 57, 59, 67, 71,  0, 48, 16,
       55, 30, 27, 68,  1, 61, 80, 76, 66, 43, 44, 77, 72, 32, 78, 75, 33,
       41, 65, 49, 18, 17, 58, 51, 14, 13, 15, 38, 60, 79, 29, 28, 54, 20,
       19, 31, 81, 84, 52, 26, 50, 34, 35, 53, 40, 89, 36, 73,  7, 37,  8,
        4, 69, 42, 45, 90, 24, 25, 74, 22,  9, 83, 88, 11,  6,  3,  5,  2,
       39, 23, 10, 86, 87])

#### There are some patients in this cohort that are 90 years old. Let's remove the values above 89 and add the 'age_at_imaging_gt89' column to account for them:

In [ ]:
studies_b1.loc[studies_b1['age_at_imaging'] >= 90, 'age_at_imaging_gt89'] = 'Yes'

In [ ]:
studies_b1['age_at_imaging_gt89'].fillna('No', inplace = True)

In [ ]:
studies_b1.loc[studies_b1['age_at_imaging'] >= 90, 'age_at_imaging'] = np.NaN

#### Okay, we're almost done. Let's double check that the submitter ids are unique and that there are 4932 of them:

In [ ]:
studies_b1.drop_duplicates(subset='submitter_id')

,case_ids,body_part_examined,study_modality,study_uid,study_description,submitter_id,cases,study_year_shifted,age_at_imaging,days_to_study,study_year,age_at_imaging_gt89
0,302028-000002,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.6,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.6,302028-000002,False,21.0,0,2020,No
1,302028-000003,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.10,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.10,302028-000003,False,56.0,-1,2020,No
2,302028-000003,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.13,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.13,302028-000003,False,56.0,-7,2020,No
3,302028-000004,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.18,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.18,302028-000004,False,82.0,80,2020,No
4,302028-000005,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.21,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.21,302028-000005,False,46.0,-2,2020,No
...,...,...,...,...,...,...,...,...,...,...,...,...
4927,302028-004296,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.1593290,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1593290,302028-004296,False,57.0,0,2020,No
4928,302028-004297,NaN,CT,1.2.826.0.1.3680043.10.474.302028.1593332,CT CHEST W CONTRAST,1.2.826.0.1.3680043.10.474.302028.1593332,302028-004297,False,42.0,0,2020,No
4929,302028-004298,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.1595898,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1595898,302028-004298,False,29.0,0,2020,No
4930,302028-004299,CHEST,DX,1.2.826.0.1.3680043.10.474.302028.1595903,XR CHEST PORTABLE 1 VIEW,1.2.826.0.1.3680043.10.474.302028.1595903,302028-004299,False,57.0,3,2020,No
4931,302028-004300,CHEST,CR,1.2.826.0.1.3680043.10.474.302028.1595933,XR CHEST 2 VIEWS,1.2.826.0.1.3680043.10.474.302028.1595933,302028-004300,False,0.0,0,2020,No

#### Now the imaging study node for UMichigan batch 1 is ready and can be downloaded:

In [ ]:
studies_b1.to_csv('imaging_study_RSNA_20230117.csv', index = False)