### Condensing clinical files from UCSF for the use in creating the Case Node, Measurement Node, and Imaging Study Node

In [ ]:
import pandas as pd
import numpy as np

##### Grab UCSF clinical files from Wyatt (most recent 'transferred exams' and 'all covid test results' csv files). The 'all covid results' file holds the info we need for the Measurement node. The 'transferred exams' file holds the info we need for the Case node and some of the Imaging Study node. Also grab a copy of the verbose report from POSDA for your batch.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
directory1 = '/content/drive/MyDrive/transferred exams - batch 26.csv'
directory2 = '/content/drive/MyDrive/all covid test results - batch 26.csv'
directory3 = '/content/drive/MyDrive/verbose_report_batch_15.csv'

##### Convert files to pandas dataframes:

In [ ]:
df = pd.read_csv(directory3,encoding='latin1')
df_all_covid = pd.read_csv(directory2)
df_transfer = pd.read_csv(directory1)

##### Grab all unique study uids:

In [ ]:
df = df.drop_duplicates(subset=['study_instance_uid'])
df

,collection,site,patient_id,patient_age,study_instance_uid,study_date,study_description,series_instance_uid,series_date,series_description,dicom_file_type,modality,num_files
0,MIDRC-RICORD,419639,419639-000304,035Y,1.2.826.0.1.3680043.10.474.419639.299627541368...,7/17/2014,CT CHEST PULMONARY EMBOLISM (CTPE),1.2.826.0.1.3680043.10.474.419639.148738017102...,7/17/2014,1.25mm Ab/pel,CT Image Storage,CT,394
11,MIDRC-RICORD,419639,419639-000316,045Y,1.2.826.0.1.3680043.10.474.419639.886776666578...,6/21/2016,CT CHEST WITHOUT CONTRAST,1.2.826.0.1.3680043.10.474.419639.108754613152...,6/21/2016,SUPINE,CT Image Storage,CT,2
27,MIDRC-RICORD,419639,419639-000368,065Y,1.2.826.0.1.3680043.10.474.419639.253295801576...,11/24/2019,CT CHEST WITHOUT CONTRAST,1.2.826.0.1.3680043.10.474.419639.109801462251...,11/24/2019,SAG 5X5,CT Image Storage,CT,76
44,MIDRC-RICORD,419639,419639-000376,070Y,1.2.826.0.1.3680043.10.474.419639.270847717950...,9/2/2015,CT CHEST PULMONARY EMBOLISM (CTPE),1.2.826.0.1.3680043.10.474.419639.110128152178...,9/2/2015,SAG 1X1,CT Image Storage,CT,358
62,MIDRC-RICORD,419639,419639-000382,050Y,1.2.826.0.1.3680043.10.474.419639.604754644445...,4/17/2018,CT CHEST WITH CONTRAST,1.2.826.0.1.3680043.10.474.419639.107226869350...,4/17/2018,1.25mm Neck,CT Image Storage,CT,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,MIDRC-RICORD,419639,419639-002949,035Y,1.2.826.0.1.3680043.10.474.419639.122477520455...,1/29/2016,CTA CORONARY,1.2.826.0.1.3680043.10.474.419639.175782334106...,1/29/2016,ALL PHASES,CT Image Storage,CT,1024
1349,MIDRC-RICORD,419639,419639-002965,050Y,1.2.826.0.1.3680043.10.474.419639.147615528554...,3/19/2020,CT CHEST WITH CONTRAST,1.2.826.0.1.3680043.10.474.419639.115088919792...,3/19/2020,Bone Recon,CT Image Storage,CT,68
1372,MIDRC-RICORD,419639,419639-002968,090Y,1.2.826.0.1.3680043.10.474.419639.783889042802...,9/22/2013,CT CHEST WITHOUT CONTRAST,1.2.826.0.1.3680043.10.474.419639.119120677021...,9/22/2013,Spine Cor 1x1mm,CT Image Storage,CT,211
1395,MIDRC-RICORD,419639,419639-002973,045Y,1.2.826.0.1.3680043.10.474.419639.195307325715...,7/30/2018,CT ESOPHAGRAM,1.2.826.0.1.3680043.10.474.419639.209594012556...,7/30/2018,pre con,CT Image Storage,CT,295
1397,MIDRC-RICORD,419639,419639-002980,070Y,1.2.826.0.1.3680043.10.474.419639.364922260159...,9/9/2015,CT CHEST PULMONARY EMBOLISM (CTPE),1.2.826.0.1.3680043.10.474.419639.126466807956...,9/9/2015,PE/AB/PEL SCOUT,CT Image Storage,CT,2

##### Remove unecessary columns from dataframe:

In [ ]:
df = df.drop(columns=['collection', 'site', 'patient_age', 'study_date', 'study_description', 'series_instance_uid', 'series_date', 'series_description', 'dicom_file_type','modality', 'num_files'])

In [ ]:
df_transfer

,Anon Acc #,Anon Age,Anon Exam Date/Time,Anon Exam Description,Anon MRN,Anon Sex,Anon Study UID,Anon Image Count,Ethnicity,Race,Modality,Zip Code,Symptomatic,Result,Anon First Eligible Result Date,Specimen Source,Upload Date
0,36406,69.80,January 24 2019 12:49:18 AM,XR CHEST 1 VIEW AP,419639-001142,F,1.2.826.0.1.3680043.10.474.419639.250183241891...,1,Not Hispanic or Latino,White or Caucasian,CR,94102.0,YES,NOT DETECTED,4/14/2018,Pooled NP/OP Swab,6/10/2021
1,17760,69.12,January 03 2014 12:03:24 PM,CT CHEST WITHOUT CONTRAST,419639-004685,F,1.2.826.0.1.3680043.10.474.419639.197643283723...,1159,Not Hispanic or Latino,Asian,CT,95747.0,YES,NOT DETECTED,1/2/2014,Pooled NP/OP Swab,10/15/2020
2,13136,63.50,November 16 2016 09:17:55 AM,XR CHEST 1 VIEW AP,419639-001509,F,1.2.826.0.1.3680043.10.474.419639.330723897774...,1,Not Hispanic or Latino,Asian,DX,94804.0,YES,NOT DETECTED,10/6/2016,Tracheal Aspirate,10/14/2020
3,20490,56.50,August 28 2017 06:53:14 PM,CT CHEST PULMONARY EMBOLISM (CTPE),419639-005197,M,1.2.826.0.1.3680043.10.474.419639.231589186627...,1305,Not Hispanic or Latino,White or Caucasian,CT,94121.0,SUSPECTED,NOT DETECTED,7/30/2017,Pooled NP/OP Swab,1/17/2021
4,43770,56.04,September 24 2017 01:30:16 PM,CT CHEST WITHOUT CONTRAST,419639-001020,M,1.2.826.0.1.3680043.10.474.419639.119629279978...,1142,Not Hispanic or Latino,Asian,CT,94118.0,YES,NOT DETECTED,7/24/2016,Pooled NP/OP Swab,7/1/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43322,19911,68.94,November 30 2014 05:56:11 PM,XR CHEST 1 VIEW AP,419639-005142,F,1.2.826.0.1.3680043.10.474.419639.198520915850...,1,Not Hispanic or Latino,White or Caucasian,CR,94122.0,YES,NOT DETECTED,11/30/2014,Pooled NP/OP Swab,1/14/2021
43323,51084,70.94,April 27 2015 03:13:37 PM,CT CHEST PULMONARY EMBOLISM (CTPE),419639-011874,M,1.2.826.0.1.3680043.10.474.419639.127326549021...,1100,Not Hispanic or Latino,Black or African American,CT,94116.0,YES,NOT DETECTED,4/27/2015,Bilateral Anterior Nares +/- OP Swab,1/7/2022
43324,39077,83.74,March 24 2020 12:04:59 AM,XR CHEST 1 VIEW AP,419639-007101,F,1.2.826.0.1.3680043.10.474.419639.130722631033...,1,Not Hispanic or Latino,White or Caucasian,DX,94115.0,YES,NOT DETECTED,12/17/2019,Pooled NP/OP Swab,6/10/2021
43325,12207,37.90,December 09 2018 08:26:57 AM,XR CHEST 1 VIEW AP,419639-003181,F,1.2.826.0.1.3680043.10.474.419639.149835290241...,2,Not Hispanic or Latino,Asian,DX,94566.0,YES,NOT DETECTED,11/25/2018,Pooled NP/OP Swab,10/14/2020
43326,32569,57.19,October 25 2015 02:32:05 AM,XR CHEST 1 VIEW AP,419639-004254,M,1.2.826.0.1.3680043.10.474.419639.333577753842...,2,Hispanic or Latino,NaN,DX,95111.0,YES,NOT DETECTED,12/22/2014,NaN,6/10/2021

##### Merge transferred exam information with batch data:

In [ ]:
df_leftover = df.merge(df_transfer, left_on='study_instance_uid',right_on='Anon Study UID', how='inner')

In [ ]:
df_leftover

,patient_id,study_instance_uid,Anon Acc #,Anon Age,Anon Exam Date/Time,Anon Exam Description,Anon MRN,Anon Sex,Anon Study UID,Anon Image Count,Ethnicity,Race,Modality,Zip Code,Symptomatic,Result,Anon First Eligible Result Date,Specimen Source,Upload Date
0,419639-000304,1.2.826.0.1.3680043.10.474.419639.299627541368...,1070,36.99,July 17 2014 01:36:40 PM,CT CHEST PULMONARY EMBOLISM (CTPE),419639-000304,M,1.2.826.0.1.3680043.10.474.419639.299627541368...,2778,Hispanic or Latino,NaN,CT,94558.0,YES,NOT DETECTED,7/15/2014,Pooled NP/OP Swab,7/18/2020
1,419639-000316,1.2.826.0.1.3680043.10.474.419639.886776666578...,1110,44.73,June 21 2016 01:48:45 PM,CT CHEST WITHOUT CONTRAST,419639-000316,M,1.2.826.0.1.3680043.10.474.419639.886776666578...,5448,Not Hispanic or Latino,White or Caucasian,CT,94122.0,YES,NOT DETECTED,7/9/2016,Nasopharyngeal Swab,7/18/2020
2,419639-000368,1.2.826.0.1.3680043.10.474.419639.253295801576...,1235,66.72,November 24 2019 07:14:48 PM,CT CHEST WITHOUT CONTRAST,419639-000368,M,1.2.826.0.1.3680043.10.474.419639.253295801576...,4019,Not Hispanic or Latino,Black or African American,CT,94115.0,YES,NOT DETECTED,11/25/2019,Pooled NP/OP Swab,7/18/2020
3,419639-000376,1.2.826.0.1.3680043.10.474.419639.270847717950...,1257,70.46,September 02 2015 08:41:12 PM,CT CHEST PULMONARY EMBOLISM (CTPE),419639-000376,F,1.2.826.0.1.3680043.10.474.419639.270847717950...,2786,Not Hispanic or Latino,White or Caucasian,CT,94803.0,YES,NOT DETECTED,9/5/2015,Pooled NP/OP Swab,7/18/2020
4,419639-000382,1.2.826.0.1.3680043.10.474.419639.604754644445...,1270,51.79,April 17 2018 05:55:04 AM,CT CHEST WITH CONTRAST,419639-000382,M,1.2.826.0.1.3680043.10.474.419639.604754644445...,4348,Hispanic or Latino,Asian,CT,94080.0,YES,NOT DETECTED,5/11/2018,Nasopharyngeal Swab,7/18/2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,419639-002949,1.2.826.0.1.3680043.10.474.419639.122477520455...,10391,32.94,January 29 2016 12:48:46 PM,CTA CORONARY,419639-002949,F,1.2.826.0.1.3680043.10.474.419639.122477520455...,2380,NaN,NaN,CT,NaN,YES,NOT DETECTED,11/1/2015,NaN,7/18/2020
76,419639-002965,1.2.826.0.1.3680043.10.474.419639.147615528554...,10509,50.77,March 19 2020 10:46:40 AM,CT CHEST WITH CONTRAST,419639-002965,M,1.2.826.0.1.3680043.10.474.419639.147615528554...,2794,Hispanic or Latino,American Indian or Alaska Native,CT,94109.0,YES,NOT DETECTED,3/19/2020,Pooled NP/OP Swab,7/18/2020
77,419639-002968,1.2.826.0.1.3680043.10.474.419639.783889042802...,10537,90.00,September 22 2013 11:17:59 PM,CT CHEST WITHOUT CONTRAST,419639-002968,F,1.2.826.0.1.3680043.10.474.419639.783889042802...,3184,Not Hispanic or Latino,Black or African American,CT,94103.0,YES,NOT DETECTED,10/22/2013,Pooled NP/OP Swab,7/18/2020
78,419639-002973,1.2.826.0.1.3680043.10.474.419639.195307325715...,10542,43.88,July 30 2018 08:36:56 PM,CT ESOPHAGRAM,419639-002973,M,1.2.826.0.1.3680043.10.474.419639.195307325715...,2678,Not Hispanic or Latino,White or Caucasian,CT,94122.0,YES,NOT DETECTED,8/7/2018,Pooled NP/OP Swab,7/18/2020
79,419639-002980,1.2.826.0.1.3680043.10.474.419639.364922260159...,10558,69.00,September 09 2015 03:19:52 PM,CT CHEST PULMONARY EMBOLISM (CTPE),419639-002980,F,1.2.826.0.1.3680043.10.474.419639.364922260159...,2794,Not Hispanic or Latino,Asian,CT,94118.0,YES,NOT DETECTED,9/9/2015,Pooled NP/OP Swab,7/18/2020

##### Now we have one of the input files ready with the study/case information:

In [ ]:
df_leftover.to_csv('studies_batch_16_clinical.csv', index = False)

##### Now let's create the input file that will hold the covid measurements:

In [ ]:
df_all_covid

,Anon Result Date,Anon MRN,PATIENT_SYMPTOMATIC,RESULT,SPECIMEN_SOURCE,MIDRC Test Method
0,5/15/2010,419639-000836,YES,NOT DETECTED,Mid Nasal/OP Swab,RT-PCR
1,6/4/2010,419639-004320,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
2,6/4/2010,419639-000538,YES,DETECTED,Pooled NP/OP Swab,RT-PCR
3,6/20/2010,419639-002514,YES,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
4,6/23/2010,419639-012710,NaN,NOT DETECTED,NaN,RT-PCR
...,...,...,...,...,...,...
82373,1/11/2022,419639-007865,YES,NOT DETECTED,Bilateral Anterior Nares +/- OP Swab,RT-PCR
82374,1/17/2022,419639-004204,NaN,NOT DETECTED,NaN,Rapid COVID19 test
82375,2/4/2022,419639-013066,YES,NOT DETECTED,NP/OP Swab,RT-PCR
82376,2/8/2022,419639-007798,NO,NOT DETECTED,Bilateral Anterior Nares +/- OP Swab,RT-PCR
82377,3/28/2022,419639-005152,NaN,NOT DETECTED,Nasal Swab,Rapid COVID19 test

In [ ]:
df_all_covid.rename(columns={'Anon MRN':'Anon_MRN'}, inplace=True)

##### Locate all the cases we need in df_all_covid:

In [ ]:
cases_needed = df_all_covid.loc[df_all_covid.Anon_MRN.isin(df_leftover['Anon MRN'])]

In [ ]:
df_leftover.rename(columns={'Anon MRN':'Anon_MRN'}, inplace=True)

In [ ]:
cases_needed

,Anon Result Date,Anon_MRN,PATIENT_SYMPTOMATIC,RESULT,SPECIMEN_SOURCE,MIDRC Test Method
59,8/26/2010,419639-000856,YES,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
62,9/11/2010,419639-000856,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
144,10/9/2010,419639-000856,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
229,10/2/2010,419639-000856,YES,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
235,10/10/2010,419639-000856,NO,NOT DETECTED,Tracheal Aspirate,RT-PCR
...,...,...,...,...,...,...
81054,6/26/2019,419639-001336,NaN,DETECTED,NaN,RT-PCR
81597,4/6/2020,419639-002965,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
81797,7/20/2020,419639-002965,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
81958,10/15/2020,419639-002965,NaN,NOT DETECTED,NaN,RT-PCR
82098,1/29/2021,419639-002965,NaN,NOT DETECTED,Nasal Swab,Rapid COVID19 test

In [ ]:
cases_all_covid = cases_needed.drop_duplicates(subset=['Anon_MRN'])
cases_all_covid = cases_all_covid['Anon_MRN']

In [ ]:
cases_all_covid

59       419639-000856
295      419639-001334
363      419639-000634
916      419639-000579
1128     419639-000397
             ...
52221    419639-000423
53241    419639-000368
56149    419639-002965
60626    419639-000911
76675    419639-001152
Name: Anon_MRN, Length: 75, dtype: object

In [ ]:
cases_needed = cases_needed.sort_values(by=['Anon_MRN'])

In [ ]:
cases_needed

,Anon Result Date,Anon_MRN,PATIENT_SYMPTOMATIC,RESULT,SPECIMEN_SOURCE,MIDRC Test Method
18123,7/15/2014,419639-000304,YES,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
59414,7/9/2016,419639-000316,YES,NOT DETECTED,Nasopharyngeal Swab,RT-PCR
36840,7/22/2016,419639-000316,YES,NOT DETECTED,Tracheal Aspirate,RT-PCR
53241,1/3/2020,419639-000368,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
74353,11/27/2019,419639-000368,YES,NOT DETECTED,Oropharyngeal Swab,RT-PCR
...,...,...,...,...,...,...
58040,9/17/2018,419639-002973,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
56968,10/21/2018,419639-002973,YES,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
54574,7/19/2018,419639-002973,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
51646,9/13/2016,419639-002980,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
37838,9/9/2015,419639-002980,YES,NOT DETECTED,Pooled NP/OP Swab,RT-PCR

##### Grab a list of all the cases from previous batches:

In [ ]:
directory4 = '/content/drive/MyDrive/cases_b1_b2_b3_b4_b5_b6_b7_b8_b9_b10_b11_b12_b13_b14.csv'

In [ ]:
df4 = pd.read_csv(directory4)
df4

               case
0     419639-000071
1     419639-000115
2     419639-000150
3     419639-000410
4     419639-000448
...             ...
9875  419639-005033
9876  419639-005035
9877  419639-005037
9878  419639-005038
9879  419639-005039

[9880 rows x 1 columns]

##### Locate the unique rows that have yet to be submitted for the cases in your batch:

In [ ]:
new_covid_results = cases_needed.loc[~cases_needed.Anon_MRN.isin(df4['case'])]

In [ ]:
new_covid_results

,Anon Result Date,Anon_MRN,PATIENT_SYMPTOMATIC,RESULT,SPECIMEN_SOURCE,MIDRC Test Method
916,4/7/2011,419639-000579,YES,NOT DETECTED,NaN,RT-PCR
31886,8/17/2014,419639-000701,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
26918,3/2/2014,419639-000701,YES,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
41255,7/21/2015,419639-000701,NaN,NOT DETECTED,Nasal Swab,Rapid COVID19 test
11535,2/25/2013,419639-000814,NaN,NOT DETECTED,NaN,RT-PCR
4757,5/12/2012,419639-000814,YES,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
10831,6/9/2013,419639-000814,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
9905,4/22/2013,419639-000814,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
11210,11/14/2012,419639-000814,NaN,NOT DETECTED,NaN,RT-PCR
17902,11/7/2014,419639-001148,NaN,NOT DETECTED,Nasal Swab,Rapid COVID19 test
16040,11/7/2014,419639-001148,NO,NOT DETECTED,Bilateral Anterior Nares +/- OP Swab,RT-PCR
5944,3/17/2013,419639-001148,YES,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
30932,2/2/2016,419639-002949,NaN,NOT DETECTED,NaN,RT-PCR
78225,11/1/2015,419639-002949,YES,NOT DETECTED,NaN,RT-PCR
33096,1/28/2016,419639-002949,NaN,NOT DETECTED,NaN,RT-PCR
28808,9/18/2016,419639-002949,NaN,NOT DETECTED,NaN,RT-PCR

##### Now the second input file is ready:

In [ ]:
new_covid_results.to_csv('all_covid_results_2022-04-20.csv', index = False)

Upload these two newly created input files to the Sharepoint location for your batch in a "input files" folder. Create a ticket for the Data Team (Woody) to create the Imaging Study, Case, and Measurement Nodes.

##### Extra: the command below gives you the unique number of cases in your batch:

In [ ]:
new_covid_results.drop_duplicates(subset=['Anon_MRN'])

,Anon Result Date,Anon_MRN,PATIENT_SYMPTOMATIC,RESULT,SPECIMEN_SOURCE,MIDRC Test Method
916,4/7/2011,419639-000579,YES,NOT DETECTED,NaN,RT-PCR
31886,8/17/2014,419639-000701,NO,NOT DETECTED,Pooled NP/OP Swab,RT-PCR
11535,2/25/2013,419639-000814,NaN,NOT DETECTED,NaN,RT-PCR
17902,11/7/2014,419639-001148,NaN,NOT DETECTED,Nasal Swab,Rapid COVID19 test
30932,2/2/2016,419639-002949,NaN,NOT DETECTED,NaN,RT-PCR